export const FETCH_MONSTERS_REQUEST = 'FETCH_MONSTERS_REQUEST';
export const FETCH_MONSTERS_SUCCESS = 'FETCH_MONSTERS_SUCCESS';
export const FETCH_MONSTERS_FAILURE = 'FETCH_MONSTERS_FAILURE';

export const NEW_MONSTER_REQUEST = 'NEW_MONSTER_REQUEST';
export const NEW_MONSTER_SUCCESS = 'NEW_MONSTER_SUCCESS';
export const NEW_MONSTER_FAILURE = 'NEW_MONSTER_FAILURE';

export const FETCH_CHARACTERS_REQUEST = 'FETCH_CHARACTERS_REQUEST';
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_FAILURE = 'FETCH_CHARACTERS_FAILURE';

export const FETCH_ENCOUNTERS_REQUEST = 'FETCH_ENCOUNTERS_REQUEST';
export const FETCH_ENCOUNTERS_SUCCESS = 'FETCH_ENCOUNTERS_SUCCESS';
export const FETCH_ENCOUNTERS_FAILURE = 'FETCH_ENCOUNTERS_FAILURE';
